- README.md
- index.js
- package.json
- This change allows us to npm install commands on workspaces instead of using them as local commands which improves command reusability. We can also stop adding deps to bosco's package.json that are only used by commands
> Load plugins from npm using the bosco-command- prefix

- commands/run.js
- commands/stop.js
- src/RunWrappers/Node.js
This will run `bosco cdn` as a command supervised by pm2, which allows it to be
stop and started as well being able to view its logs via `pm2`.
Its not an elegant solution by a long shot, however it works.
Example:
```sh
$ bosco run --cdn
$ bosco stop #This will stop cdn aswell
```
> bosco run now has --cdn command

- package.json
This package has been pinned to 2.7.0 as 2.7.1 reverts a fix with clashing argument names.
Namely this fixes `bosco cdn`
> Pinning commander's version to 2.7.0 as 2.7.1 breaks cdn

- commands/pull.js
git clone will automatically set the remote origin, so this should function as normal
> git pull for branch not always master fixes #73

- src/ExternalBuild.js
ExternalBuild: improve build and watch semantics for cdn.
* Output only when there is an error
* Log all stderr when watching
> Improve cdn

- src/RunWrappers/Node.js
If the engine is set in package.json to a version of node earlier than v0.12, bosco should still be able to parse this and find the correct interpreter.
> allow for earlier versions of node

- commands/clean-modules.js
The reason for this change is `bosco-clean` has been broken since the
introduction of `bosco clone --clean` due to how arguments are handled
this removes `bosco clean`.
A better fix would be to fix the root cause, however `bosco
clean-modules` makes more sense from the cli.
> Renaming bosco clean to bosco clean-modules

- commands/template.js
- index.js
Currently the clone script assumes that the repositories are all in the hostname `github.com`. However, if you have multiple Github accounts configured [1] you might have the hostname other than that.
The pull request adds the posibility to configure a different hostname using `bosco config set github.host` which will be used afterwards for the cloning process.
1. [Managing Multiple Git Accounts](http://mherman.org/blog/2013/09/16/managing-multiple-github-accounts/)
> Enabling custom git hostnames in repositories

- .jshintrc
- commands/s3push.js
- index.js
- src/ExternalBuild.js
- src/StaticUtils.js
- test/ExternalBuild.test.js
- test/StaticUtils.test.js
- test/TestOrganisation/projectFail/bosco-service.json
- test/boscoMock.js
- test/s3push.test.js
Improve error handling in `ExternalBuild`, `StaticUtils`, and `s3push`.  Add comprehensive tests for `ExternalBuild`, and some tests for `s3push` and `StaticUtils`.  Should fix #98.
> s3push fix

- commands/cdn.js
- src/StaticUtils.js
* Output number of sucessful and failed builds
* Output the error message for each failed build
This fixes issues I've had where `bosco cdn` keels over when a build fails, even though I don't really care about it.
@dbellizzi
> Allow ignoring errors for StaticUtils builds.

- .eslintrc
- package.json
shadow-exception deprecates itself on new version of eslint 
This resolves #117
With warm regards from [electrician](https://github.com/tes/electrician/blob/7e4d2f3d07713f6be2821dd31226d9fdd0703946/.eslintrc#L7)...
> Replace shadow-exception plugin with allow option

- commands/audit.js
got 
```
"error requiring command file: /Users/hustler/.nvm/v4.2.2/lib/node_modules/bosco/commands/audit.js: Error: Cannot find module 'nsp/lib/auditPackage' error
```
when running bosco --version
> cannot find nsp module error in bosco v0.5.1

- bin/bosco.js
- commands/run.js
- config/options.json
- src/CmdHelper.js
I've seen way too many people `bosco run`ning the s***t out of 70 repos when all they wanted to do was run the project on their cwd. 
Note that we will still run all if you call `bosco run` from the workspace root folder
@geophree
> Only run the current project when in service folder

- commands/cdn.js
So projects they delete before generating, so watching will ignore those files... Listening to the created and change event fix the issue. Should fix issue as well #123
> fix watch when the file is deleted instead of modifying

- commands/cdn.js
- config/options.json
- package.json
under -l or --browser-sync option, proxied to local page composer
```
bosco cdn -w app-home -l
```
simplest addition of live reload I could think of adding without impacting every projects build chain
we should look at gulp builds as currently the fact it wipes out *all* assets on a change forces a page refresh, if it was more selective (e.g. only building css if css changes) it would use the inject / live-reload instead of the page refresh
> Add browser sync

- README.md
- commands/clone.js
- commands/team.js
- src/RunListHelper.js
This Pull Request enable the support for github enterprise with dosco.
I'm just leveraging the basic capabilities of octonode to pass in an hostname for the enterprise. 
If it's not filled in (the default case),it will default to standard github.
Thanks :)
> [Feature] Add support for github enterprise

- src/RunListHelper.js
A log line to make it clear that there's been a failure to load the service config. Doesn't stop the continuation of the running of the command in progress.
> Log if no access to service config

- package.json
Migrated pre-commit checks from `pre-commit` to `husky` for better nvm support
> Migrated pre-commit checks from `pre-commit` to `husky`

- commands/run.js
Renamed --dont to --dev as the common case is that you don't want to start the service automatically when you are actively developing that specific service
> Renamed bosco run --dont to bosco run --dev

- commands/run.js
- commands/stop.js
- index.js
- src/RunListHelper.js
- src/RunWrappers/Docker.js
- src/RunWrappers/DockerUtils.js
Break the start process up into three groups:
- Docker services
- Node services
- Node apps
Start each group in series, but within each group start each thing in parallel up to cpu limit.  Initially did crazy things with Docker when trying to start 8 docker containers at once, but seems ok now.
On `app-home`, which has the following set of services when started:
```
┌────────────────────────────────────────────────────────────┬──────────┬──────────┬────────────┬──────────┐
│ Node Service                                               │ PID      │ Status   │ Mode       │ Watch    │
│ service-page-composer                                      │ 40855    │ online   │ fork_mode  │          │
│ service-site-assets                                        │ 37789    │ online   │ fork_mode  │ …
```
> Modify start and stop to speed up by running things more in parallel

- commands/cdn.js
- index.js
- src/ExternalBuild.js
- src/ExternalBuilders/ExecBuild.js
- src/ExternalBuilders/SpawnWatch.js
- src/ExternalBuilders/utils.js
- test/ExternalBuild.test.js
- test/TestOrganisation/projectFail/bosco-service.json
- test/boscoMock.js
Rolls up output changes from @bettiolo, should make ongoing watching and console output much more usable.
> Refactor of external build to make the output cleaner

- src/ExternalBuilders/utils.js
- test/ExternalBuild.test.js
- test/TestOrganisation/project3/bosco-service.json
- test/TestOrganisation/projectEmpty/bosco-service.json
- test/TestOrganisation/projectFail/bosco-service.json
`checkDelay` and related timer are not used anymore.
It has been replaced by `isBuildFinished` sync method: 
https://github.com/tes/bosco/blob/master/src/ExternalBuilders/SpawnWatch.js#L47-L62
> Removing unused option `checkDelay`

- commands/ps.js
Columns will fill available terminal space until a minimum width of 20 columns:
> bosco ps will now display fluid columns

- commands/branches.js
based off of status command.
use 'git branch --list' to show all branches, and checked out branch is marked with a '*'
only show results for branches not on master
> add new command to report on repos not on master

- commands/install.js
It's possible (likely?) I've missed something here, but the `bosco install` command now works in a single repo on my machine.
cc/ @dmorgantini @cliftonc
> return the list of repos, not an unresolved chain

- src/RunWrappers/Node.js
Without this stderr can't be parsed and produces an error like:
```
error = options.name + ' nvm failed with: ' + data.replace('\n', '') + ', use -i option to install missing node versions!';
^
TypeError: data.replace is not a function
```
> utf8 encode stderr

- commands/run.js
This change makes it possible to run `docker-compose` services via boscoas described in the [README](https://github.com/tes/bosco/tree/enable_running_docker_compose#docker-compose). 
Trying to do so without this code gives the following error:
```
Bosco: Unable to run services of un-recognised type: jobs-containers. Check their bosco-service.json configuration.
```
> Allow `docker-compose` as a run type

- commands/cdn.js
If running `bosco cdn` from within a project that has no assets defined in the `bosco-service.json`, it crashes with the following error:
```
[05:12:47] Bosco: Starting pseudo CDN on port: 7334
[05:12:47] Bosco: 0 out of 0 succeeded.
[05:12:47] Bosco: Server is listening on 7334
/Users/rnewstead/.nvm/versions/node/v6.2.1/lib/node_modules/bosco/commands/cdn.js:105
return response.end(staticAssets.formattedAssets);
^
TypeError: Cannot read property 'formattedAssets' of undefined
at Server.<anonymous> (/Users/rnewstead/.nvm/versions/node/v6.2.1/lib/node_modules/bosco/commands/cdn.js:105:41)
at emitTwo (events.js:106:13)
at Server.emit (events.js:191:7)
at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
```
It …
> Don't crash `bosco cdn` if the project has no static assets

- commands/run.js
- src/RunListHelper.js
'--docker-only' is an option of 'bosco run' command that starts docker only dependencies, but do not start the services.  
The use case is to restart docker only dependencies when docker crashes while all the services are already running via pm2.
> Add --docker-only as option to bosco run command

- commands/s3push.js
https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/
https://code.facebook.com/posts/557147474482256
Can't see any risk for us given we always have the build number as part of the URL, and the file version number in the URL for any 3rd party library.
This only applies to S3 files, not to local cdn.
> Add cache-control: immutable given we always version by URL

- commands/run.js
- commands/stop.js
@cliftonc, we found that there are several repos in our teams that do not have a bosco-service.json, so `bosco start` and `bosco stop` are failing on 404s.
Given that the conditions that would get us to this code is for svcConfig to be undefined, we think that this fix might be just what we need to make it work.
It appears to work on a patched version.
@albertodotcom
> assign a new value for the whole svcConfig, not just the .service

- commands/run.js
- commands/stop.js
This PR fixes the error that occurs when running the `run` or `stop` command by creating an empty object that is passed into getServiceDockerConfig method
> Create an empty svcConfig object to pass in getServiceDockerConfig

- commands/install.js
bosco morning runs yarn and this may update some dependency, generating a new yarn.lock.
Next time bosco morning won't pull any change because there are unstaged changes (the lockfile).
This proposed change avoids creating lockfile from bosco.
As an alternative we could run it "--production" instead.
@tomruttle please chime in
> added --pure-lockfile option to yarn

- commands/clone.js
- commands/run.js
- commands/team.js
- index.js
- src/RunListHelper.js
The existing code made wrong assumptions on the return type of the getTeam method, fixed that and improved error messaging.
When running `bosco team`:
when running `bosco run -d`
> Improvements to missing team errors

- commands/help.js
Since the `man` folder was [flattened](https://github.com/tes/bosco/commit/951ed2293955496add90dd12c3eac7814cd6d686) running `bosco help $cmd` gives the following error:
```
No entry for bosco-run in section 3 of the manual
```
We no longer need to set `env.MANPATH` as it has been flattened so the path will be the default. This simplifies the code a lot.
We also get a deprecation warning when running `bosco help`:
```
(node:34232) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
```
This PR fixes the deprecation warning by using `stdio` instead of `customFds`.
> Fix `help` command

- config/options.json
- index.js
I was recently caught out because my local `nginx` was misbehaving and I didn't notice that `bosco` was out of date (on the node version used for the project I was running). Noticing would have saved me a heap of time, so from now on I want Bosco to be stricter with me.
`bosco` already checks to see whether you are running the latest version. This PR introduces a 'strict mode', which will kill the current process if you're not.
```js
// bosco config
{
// ...
"strict": true
}
```
Note that the version check is asynchronous, so there will be times when `bosco` doesn't find out in time that it's out of date.
Feel free to suggest better names for the setting 🐶
/cc @cliftonc @andy-duncan
> Ensure latest version

- index.js
If NVM is installed from git or homebrew then the package.json for NVM
may not exist, resulting in bosco failing to work.  The version check
was to ensure at least nvm 0.21.0 was installed for some required API changes.
0.21.0 was released over 3 years ago so it's safe to assume new users
will definitely have a newer version and those who don't will be able to
figure it out.
> Remove NVM version dependency check

- .gitignore
- package.json
- Remove unclear duplication in npm scripts and rely on `pre` scripts to
indicate dependencies
- Remove unused npm scripts
> Upgrade from istanbul to nyc and tidy up scripts

- commands/cdn.js
- config/options.json
- package-lock.json
- package.json
- src/AssetHelper.js
This PR removes `browsersync` functionality:
- `browsersync` has a [security vulnerability](https://npmjs.com/advisories/786 ) (via `micromatch` and `braces`), but the [patch](https://github.com/BrowserSync/browser-sync/pull/1659) has not been merged yet
- It's currently an undocumented feature in `bosco`, so it's unlikely to have much usage
- I plan to bump the major version when releasing this change
> Remove browsersync functionality

- config/options.json
- index.js
- package.json
- src/RunWrappers/Node.js
- This will allow for NVM to be unavailable and execute commands against the
system wide node version
> Add --system-node flag to skip NVM use

- package-lock.json
- package.json
- src/RunWrappers/DockerUtils.js
Lately I've been getting a few timeouts while running bosco deps.
Bosco will consider a service up when it can connect to the service port and the connection will stay open for more than 200ms.
Two things are failing that check:
1- `infra-rabbitmq` is disconnecting straight away clients that are connecting too aggressively (so we never reach 200ms connection time)
2- some services are sending data when we connect to the port. So when we call `socket.end()` after 200ms it will just [half-close the socket](https://nodejs.org/api/net.html#net_socket_end_data_encoding_callback) and it won't ever reach the  check that is happening `on('close')`
To fix those two problems, I've updated the retry connection time from 50ms to 200ms, and I've changed the logic to consider a service up if it's …
> Improve timeout detection
