- commands/run.js
Causes an error in certain situations (happened to me this morning)
> Handle missing service config better

- commands/run.js
- Creates a reverse dependecy tree to make sure we know who is calling the dead service
This commit was created 10 days ago but forget to create the PR :disappointed:. This is the verbose version of https://github.com/tes/bosco/commit/f9732f6871568c25f6da0c14fc8226919436b5e4
> Error out if a service depends on another service that does not exist

- commands/team.js
The team sync was only retrieving the first 30 teams (github default page size). I'm in more than 30 teams so when I was newly added to the "profiles" team bosco kept complaining it couldn't find the team I was in!
This PR alters team sync so that it retrieves the first page of teams, and then retrieves any remaining pages in parallel (if there are any).
> Fix team sync

- commands/unlink.js
Referses the effects of `bosco link` by unlinking all modules (or a subset using the -r syntax).
Takes ages when you run it - be ready for a coffee break.
> Add `unlink` command

- commands/run.js
- commands/stop.js
- src/RunWrappers/DockerCompose.js
A couple of small hacks in docker stop, but not too bad
> Added support for docker-compose

- src/RunWrappers/DockerUtils.js
Is there a reason we didn't do this before?
> Ignore alwaysPull

- commands/cdn.js
Local tests pass, and a resource page loads correctly when it's running.
I don't know all the ways the cdn is used, so there may be more testing that needs to happen.
@cliftonc would you take a look?
> cdn: Clean up code.

- commands/cdn.js
(prompted by the need to serve font files)
> Local CDN allows cross-origin requests

- README.md
- commands/cdn.js
- commands/install.js
- commands/run.js
- commands/s3push.js
- commands/stop.js
- index.js
- src/ExternalBuild.js
- src/RunWrappers/Node.js
- test/boscoMock.js
- test/s3push.test.js
Basically everything just honors the .nvmrc and it uses nvm properly everywhere (nvm use / nvm which).
> Install, run and cdn all now honor .nvmrc, removed old bosco-service nodeVersion

- src/RunWrappers/Node.js
We still have some projects with v0.12.9 that doesn't support yet startsWith
> startsWith is not supported in node v0.12.9

- src/ExternalBuild.js
- test/ExternalBuild.test.js
- test/TestOrganisation/project3/bosco-service.json
@cliftonc would you have a quick look at this, please?
> Run 'nvm' and 'nvm use'  before watch commands

- commands/cdn.js
- commands/install.js
- commands/pull.js
- commands/run.js
- commands/stop.js
- src/CmdHelper.js
- src/RunListHelper.js
When morning command is run within service directory, it runs limited to the service and it's dependencies rather than entire workspace.
> In-service morning

- .travis.yml
- test/bosco.test.js
> Make tests run on node v4+

- commands/cdn.js
- commands/s3push.js
> add fileTypesWhitelist to asset commands

- src/RunWrappers/Node.js
... until https://github.com/nodejs/node/issues/7342 is resolved.
> workaround for https://github.com/tes/bosco/issues/152

- .editorconfig
should match current coding style
> Added .editorconfig to have consistent coding across editors

- bin/bosco.js
- commands/cdn.js
- commands/clone.js
- commands/pull-docker.js
- commands/run.js
- commands/s3delete.js
- commands/s3push.js
- commands/stop.js
- commands/tail.js
- package.json
- src/Minify.js
- src/RunListHelper.js
- src/RunWrappers/Docker.js
- src/RunWrappers/DockerUtils.js
- src/RunWrappers/Node.js
- src/StaticUtils.js
- test/StaticUtils.test.js
see https://github.com/apocas/docker-modem/pull/64
> Updated Dockerode to get better error messages (from docker-modem)

- commands/team.js
Now team names are sorted lexicographically and the actual team setup command works.
> bosco team command fixes

- package.json
- src/RunWrappers/Node.js
> Upgrade PM2 and use no auto-restart

- commands/install.js
- commands/pull-git.js
- src/RunListHelper.js
For #178 - untested due to train wifi.
> Fix to ensure we dont pull or install remote repos

- commands/run.js
- commands/stop.js
- index.js
- src/RunListHelper.js
- src/RunWrappers/Node.js
> Improvements to run and stop to make the output more usable

- src/Minify.js
> fixing duplicated css

- commands/history.js
@glasseyes42 I know this is not exactly what you are looking for, but might still be quite useful in a number of instances. Maybe we should have a team that has ALL the repos in it?  ;-)
not totally convinced that 'history' is the right name for it, but I thought it was a start in the right direction.
> new command for running 'git log -S' against all repos in the team

- commands/install.js
maybe we should get either bosco.options.nvmUse or bosco.options.nvmUseDefault from getInterpreter as we seems to be doing interpreter && bosco.options.nvmUse || bosco.options.nvmUseDefault logic in a few places. but that's for another day
> Respect nvmrc when using Yarn to install dependencies

- commands/install.js
- index.js
- src/RunWrappers/Node.js
it skips it if the last version is unknown, and just assume the current version is the last version used.
> reset node_modules when current node version is different from the last version used

- commands/cdn.js
- index.js
- src/RunWrappers/Docker.js
These changes help with local https, but they're not ready to merge yet.
> [DO NOT MERGE] Changes to facilitate local https.

- commands/config.js
This is to make rolling out the changes for tes/infra#1810 easier.
> Add bosco config clear <key>. and bosco get deals with unset keys

- src/RunWrappers/Docker.js
Since we moved to using the service-router in all environment options for endpoints, services running in docker have been unable to communicated via nginx. This is due to <service-name>.service.local.tescloud.com resolving inside a container to localhost. 
This change adds the depended upon services to the hosts list with the host machine ip.
> Use dependsOn list for a service to add more ExtraHosts definitions

- src/RunWrappers/DockerUtils.js
We can either use force for removal, or just check if it's running and stop it before removing
> If container running, stop it before removal #247

- package-lock.json
- package.json
Update dependencies to remove dependabot alerts
> Fix audit issues
